environment:
  # Note: if updating to Node 10, use at least 10.5.0 to include a fix for
  # https://github.com/nodejs/node/issues/20297
  nodejs_version: "8.9.2" # Same version as used in CircleCI.

matrix:
  fast_finish: true

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install
  # Appveyor (via chocolatey) cannot use older versions of Chrome:
  # https://github.com/chocolatey/chocolatey-coreteampackages/tree/master/automatic/googlechrome
  - npm run webdriver-update-appveyor

test_script:
  - node --version
  - npm --version
  - npm test
  - npm run test-large

build: off
deploy: off

cache:
  - node_modules -> package-lock.json
